#!/bin/bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

source "$DIR/models.conf"

if [[ "$HEY_HOSTNAME" == 'groq' ]]; then
  # Only set if not already defined
  [[ -z "$HEY_MODEL" ]] && HEY_MODEL="$GROQ_MODEL"
  [[ -z "$HEY_MODEL_SOTA" ]] && HEY_MODEL_SOTA="$GROQ_MODEL_SOTA"
  [[ -z "$HEY_MODEL_SEARCH" ]] && HEY_MODEL_SEARCH="$GROQ_MODEL_SEARCH"
  [[ -z "$HEY_MODEL_RP" ]] && HEY_MODEL_RP="$GROQ_MODEL_RP"
  [[ -z "$HEY_MODEL_LIQUID" ]] && HEY_MODEL_LIQUID="$GROQ_MODEL_LIQUID"
  [[ -z "$HEY_MODEL_CODE" ]] && HEY_MODEL_CODE="$GROQ_MODEL_CODE"
  [[ -z "$HEY_MODEL_FLASH" ]] && HEY_MODEL_FLASH="$GROQ_MODEL_FLASH"
else
  # Set hostname if not already 'groq'
  [[ -z "$HEY_HOSTNAME" ]] && HEY_HOSTNAME="openrouter"
  # Only set if not already defined
  [[ -z "$HEY_MODEL" ]] && HEY_MODEL="$OPENROUTER_MODEL"
  [[ -z "$HEY_MODEL_SOTA" ]] && HEY_MODEL_SOTA="$OPENROUTER_MODEL_SOTA"
  [[ -z "$HEY_MODEL_SEARCH" ]] && HEY_MODEL_SEARCH="$OPENROUTER_MODEL_SEARCH"
  [[ -z "$HEY_MODEL_RP" ]] && HEY_MODEL_RP="$OPENROUTER_MODEL_RP"
  [[ -z "$HEY_MODEL_LIQUID" ]] && HEY_MODEL_LIQUID="$OPENROUTER_MODEL_LIQUID"
  [[ -z "$HEY_MODEL_CODE" ]] && HEY_MODEL_CODE="$OPENROUTER_MODEL_CODE"
  [[ -z "$HEY_MODEL_FLASH" ]] && HEY_MODEL_FLASH="$OPENROUTER_MODEL_FLASH"
fi
